### PR TITLE
enable offline charging

### PR DESCRIPTION
**Pull request by sub77-2016**

### CODE REVIEW

**Comment by n1kolaa** [comment]
Not working. It boot directrly to system.

**Comment by sub77-2016** [comment]
found this on note4 tree
CHARGING_ENABLED_PATH := /sys/class/power_supply/battery/batt_lp_charging

**Comment by RobertRozic** [comment]
Our phone is not note4

**Comment by faizauthar12** [comment]
and 
/sys/class/power_supply/battery/batt_lp_charging is just stop at battery 
no files batt_lp_charging
i only seen that files at samsung broadcom device 

close the commit please

**Comment by faizauthar12** [comment]
nvm
now i investigate with root explore(previous with twrp file manager)
yeah ,the file exist 
23827539165_2712d1ec98_o

O.o ,i think it exist at all samsung device

**Pull request closed without merging**
